// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeyEventData(arg1) {
  return window['go']['main']['App']['GetKeyEventData'](arg1);
}

export function GetMostPressedKey() {
  return window['go']['main']['App']['GetMostPressedKey']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsLoggerActive() {
  return window['go']['main']['App']['IsLoggerActive']();
}

export function ToggleLoggerDaemon() {
  return window['go']['main']['App']['ToggleLoggerDaemon']();
}
