// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ToggleLoggerDaemon():Promise<boolean|Error>;

export function GetKeyEventData(arg1:string):Promise<Array<main.KeyData>>;

export function GetKeysPressedIn(arg1:number):Promise<Array<main.HourEvents>>;

export function GetMostPressedKey():Promise<main.CharData>;

export function Greet(arg1:string):Promise<string>;

export function IsLoggerActive():Promise<boolean>;
